### ISSUE TITLE
Problem to use copy_classic_load_balancer

### ISSUE THREAD

**Issue by salvaitor** [aws/elastic-load-balancing-tools#20]
Hello, 
I install python 3.6 e boto3; 
i try the command "copy_classic_load_balancer.py --name elb-classic --region us-east-1 --dry-run"
and dont have success. 
Debug result: 
checking if ALB exists
2017-11-14 16:37:17,726 INFO Starting new HTTPS connection (1): elasticloadbalancing.us-east-1.amazonaws.com
Checking hard failure detector
Traceback (most recent call last):
  File "C:\Users\salvaitor\AppData\Local\Programs\Python\Python36-32\Scripts\copy_classic_load_balancer.py", line 595, in <module>
    main()
  File "C:\Users\salvaitor\AppData\Local\Programs\Python\Python36-32\Scripts\copy_classic_load_balancer.py", line 562, in main
    if passed_hardfailure_detector(elb_data):
  File "C:\Users\salvaitor\AppData\Local\Programs\Python\Python36-32\Scripts\copy_classic_load_balancer.py", line 178, in passed_hardfailure_detector
    if elb_data['LoadBalancerDescriptions'][0]['Policies']['OtherPolicies'] > 0:
TypeError: '>' not supported between instances of 'list' and 'int'

any tips?

**Comment by danlindow** [comment]
I am working on a pull request for this right now.  The following Gist should get you through for the moment though:
https://gist.github.com/danlindow/68369993bb1eaa9900be1377721a7c42

Can you give that a go and let me know if that works for you? I was able to get this created in Python36.

**Comment by salvaitor** [comment]
Thank for a quick response. 

Here is the test result (gistfile1):

checking if ALB exists
2017-11-16 09:54:59,123 INFO Starting new HTTPS connection (1): elasticloadbalancing.us-east-1.amazonaws.com
Checking hard failure detector
Checking soft failure detector
Your load balancer configuration is supported by this migration utility

**Comment by danlindow** [comment]
Perfect, this should be resolved. This was also merged into master.  

Thanks for bringing this to our attention.

**Comment by renlon** [comment]
Closing the issue as it has been fixed via https://github.com/aws/elastic-load-balancing-tools/pull/21
